### ISSUE TITLE
/altinity-kb-queries-and-syntax/ttl/ttl-group-by-examples/

### ISSUE THREAD

**Issue by oliverdding** [Altinity/altinityknowledgebase#52]
> GROUP BY section should be a prefix of a table’s ORDER BY.

Should be prefix of table’s PRIMARY KEY

**Comment by UnamedRus** [comment]
Are you sure that it doesn't work with ORDER BY?

**Comment by UnamedRus** [comment]
Thank you.

Lets [open](https://github.com/ClickHouse/ClickHouse/issues/44407) an issue in ClickHouse repo for that.
